---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-prod-ingress-fastapi
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: pressleywelsh524.coe332.tacc.cloud
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app-prod-service-fastapi
                port:
                  number: 5000
